disabled_rules: # rule identifiers to exclude from running
- force_cast
- empty_count
- identifier_name
opt_in_rules: # some rules are only opt-in
- empty_count
# Find all the available rules by running: swiftlint rules
included: # paths to include during linting. ‘--path’ is ignored if present.
- XCCov-Demo
# configurable rules can be customized from this configuration file
line_length: 200
# they can set both implicitly with an array
type_body_length:
- 300 # warning
- 400 # error
# or they can set both explicitly
file_length:
warning: 600
error: 1200
type_name:
allowed_symbols: “_”
min_length: 4 # only warning
max_length: # warning and error
warning: 50
error: 60
excluded: iPhone
cyclomatic_complexity:
warning: 15
error: 20”
